### ISSUE TITLE
Viewer - issue when opening 2 viewers at the same time

### ISSUE THREAD

**Issue by jehanneman** [liam2/larray#113] opened 2017-02-13 11:03 UTC
When opening a second viewer with a command line 'view()' in the first viewer -> a second viewer opens BUT is not responding and causes the 2 viewers to crash

**Comment by gdementen** [comment] 2017-02-13 11:08
Thanks for reporting but this is a duplicate of #109 ;-)

**Closed by gdementen** 2017-02-13 11:08 UTC
Labels: bug
